import { useCallback, useMemo } from 'react'
import { useLinks, type ChunkKey, type PinOptions, type PinnedLink } from '../contexts/LinksContext'

export interface UsePinsResult {
  pins: PinnedLink[]
  pinnedChunkKeys: Set<string>
  createPin: (
    source: ChunkKey,
    target: ChunkKey,
    sourceText: string,
    targetText: string,
    options?: PinOptions
  ) => PinnedLink
  deletePin: (pinId: string) => void
  updatePinLabel: (pinId: string, label: string) => void
  isPinned: (source: ChunkKey, target: ChunkKey) => boolean
  togglePin: (
    source: ChunkKey,
    target: ChunkKey,
    sourceText: string,
    targetText: string,
    score?: number
  ) => void
  getPinsFromChunk: (key: ChunkKey) => PinnedLink[]
}

/**
 * Hook for managing pinned links
 * Provides pin/unpin functionality and pin state tracking
 */
export function usePins(): UsePinsResult {
  const links = useLinks()

  // Build a set of pinned chunk keys for quick lookup
  const pinnedChunkKeys = useMemo(() => {
    const keys = new Set<string>()
    for (const pin of links.pins) {
      keys.add(`${pin.targetKey.filePath}:${pin.targetKey.chunkIndex}`)
    }
    return keys
  }, [links.pins])

  // Toggle pin on a chunk
  const togglePin = useCallback(
    (
      source: ChunkKey,
      target: ChunkKey,
      sourceText: string,
      targetText: string,
      score?: number
    ) => {
      // Find existing pin
      const existingPin = links.pins.find(
        (p) =>
          p.sourceKey.filePath === source.filePath &&
          p.sourceKey.chunkIndex === source.chunkIndex &&
          p.targetKey.filePath === target.filePath &&
          p.targetKey.chunkIndex === target.chunkIndex
      )

      if (existingPin) {
        links.deletePin(existingPin.id)
      } else {
        links.createPin(source, target, sourceText, targetText, {
          autoGenerated: false,
          originalScore: score,
        })
      }
    },
    [links]
  )

  return {
    pins: links.pins,
    pinnedChunkKeys,
    createPin: links.createPin,
    deletePin: links.deletePin,
    updatePinLabel: links.updatePinLabel,
    isPinned: links.isPinned,
    togglePin,
    getPinsFromChunk: links.getPinsFromChunk,
  }
}
